---
kind: Pod
apiVersion: v1
metadata:
  name: nginx1
spec:
  containers:
    - name: nginx
      image: 'nginx:1.17.3-alpine'

---
kind: Pod
apiVersion: v1
metadata:
  name: nginx2
spec:
  containers:
    - name: nginx
      image: 'nginx:1.17.3-alpine'
